
## Packages
# All the functions of R are not necessarily included in the base program, so sometimes you need to upload libraries gathering sets of related
installed.packages ("tidyr")
# functions. These packages are created and updated by R users and developers
#install.packages("tidyr") # install a new package
library(tidyr) # load a new package for your current session to be able to use the functions it contains. This needs to be done only once as long as
               # you do not close the program. You will have to run this line again for the next session)

### 4 - Data structures #############################################################################################################################

## Common data structures
# - vector: c()
# - list: list() and vector()
# - matrix: matrix()
# - data frame: data.frame()
# - array: We are not going to speak about arrays today!

#~# Exercise: Create a vector of numeric values using object_1, object_2 and object_3 and store it in object_a
object_a <- c(object_1, object_2, object_3)

# Remark: You can use pre-programmed functions to create a vector
object_a2 <- 2:10

#~# Exercise: Create a vector of numeric values between 2 and 10 by steps of 3 using seq() and store it in object_b
object_b <- seq(2, 10, 3)

# Remark: A vector can contain different types of data, but if so, everything will be automatically converted into characters


#~# Exercise: Create a matrix using object_a, object_b and object_c (have a look at help(matrix) to do so!) and store it in object_f
object_f <- matrix(data=c(object_a, object_b, object_c), nrow=3, ncol=3, byrow=FALSE)
object_f

# Remark: You can call different things in a matrix
object_f[1, ] # call a line in a matrix
object_f[, 1] # call a column in a matrix
object_f[1, 1] # call a cell in a matrix

#~# Exercise: Create a data frame using object_a, object_b, object_c and object_c and store it in object_g. Name the columns "colname_1",
# "colname_2", "colname_3", "colname_4"
object_g <- data.frame(colname_1=object_a, colname_2=object_b, colname_3=object_c, colname_4=object_c)

# Remark: You can call different things in a data.frame
object_g # the lines and columns have names you can use to select them specifically
object_g$colname_1 # call a column in a data frame
object_g$colname_1[1] # call a cell in a data frame
# You can also use the same methods than for matrices

# Some useful functions for data frames
dim(object_g) # dim() gives the dimensions of the data frame (nb of lines and columns)
nrow(object_g) # nrow() gives the number of rows
ncol(object_g) # ncol() gives the number of columns
object_h <- rbind(object_g, object_g, object_g) # rbind() combines several data frames by adding lines (use cbind() to add columns)
head(object_h) # head() shows the 6 first lines of a data frame
#View(object_h) # View() shows the data frame in a specific window where you can manipulate your data set

## Factors
# Factors are specific characters used to work with categorical variables. They are very convenient for statistical analysis and some visual
# representations but they are not easy to use!
class(object_g$colname_3)
object_g$colname_3
object_g$colname_4 <- as.factor(object_g$colname_3) # as.factor() converts objects into factors
class(object_g$colname_4)
object_g$colname_4

### 5 - R projects vs. R scripts ####################################################################################################################

## Purpose of R projects: RStudio helps you keeping track of the files generated by your project
# - All the files you generate are in the same place because RStudio sets the root directory to whichever folder your project is saved to
# - Helps organising the documents related to your project (scripts, plots, data sets, ...)
# - Easy to share: Just share the folder as a whole
# How to create a R project:
# - Click "File", 
# - Click "New project...",
# - Select "New directory",
# - Select "New project",
# - Define the name of your project folder,
# - Select the sub-directory where you want to save your project using "Browse",
# - Tick "Open in new session",
# - Click "Create Project". This will open a new R script in RStudio, you can start working on your new project.

#Working directory

#~# Exercise: Click on the floppy disk (top left of the script window) and choose the directory where you want to save your current script. Then, 
# define your working directory
setwd("/Users/Joshua/Library/CloudStorage/OneDrive-UniversityofFlorida/R input")
getwd()

### 6 - Import a data set ###########################################################################################################################

## Import a .csv data set
# The read.table() function is the most general function to import any kind of data set (.csv, .txt, ...)

#~# Exercise: Import the "2_Introduction_to_R_and_study_design_dataset.csv" data set in R (have a look at help(read.table) to do so) and store the
# data set in an object called data
data <- read.table("2_1_Introduction_to_R_dataset.csv", sep=";", dec=".", header=T)

## First manipulations of a data frame
#~# Exercise: What is the structure of "data"? What is the number of columns and lines of the "data"? What type of variables are contained in "data"?
# Convert the columns "species" and "site_id" into factors. What are the min and max number of adults in the data set? Calculate the total number of
# individuals in each capture event and store this in a new column named "total_nb" (use rowSums() to do so).
class(data)
dim(data)
class(data$capture_event_id)
str(data)
data$species <- as.factor(data$species)
data$site_id <- as.factor(data$site_id)
summary(data)
data$total_nb <- rowSums(data[ , c("inf_one", "one_to_six", "six_to_twelve", "sup_twelve", "adult", "unknown")])

#~# Exercise: How many capture events contain hartebeest? Topi? Grant's gazelle? Use table().
table(data$species)

# You can extract some columns and lines of a data set according to criteria. For instance, you can:
# - extract the capture events containing hartebeest
data_hartebeest_1 <- data[data$species=="hartebeest", ]
# - extract the capture events containing hartebeest and topi (it means the capture event shows hartebeest OR topi)
data_hartebeest_2 <- data[data$species=="hartebeest" | data$species=="topi", ]
# - extract the capture events containing hartebeest and located in site P10 (it means that the capture event shows hartebeest AND takes plane in
# site P10)
data_hartebeest_3 <- data[data$species=="hartebeest" & data$site_id=="P10", ]

#~# Exercise: Extract the captures events containing topi in a new data frame called "data_topi". Use the previous method and subset() (call this
# second data frame "data_topi_2")
data_topi <- data[data$species=="topi", ]
data_topi_2 <- subset(data, subset=(species=="topi"))


### 7 - Data visualisation ##########################################################################################################################

## Basic graphs in R
# - histogram: hist()
# - boxplot: boxplot()
# - scatter plot: plot()
# - stacked bar chart: plot() or mosaicplot()

## Histograms
#~# Exercise: Represent the number of pictures containing 0, 1, 2, 3, ... topi using data_topi. Give a title to your graph and label axes
hist(data_topi$total_nb, breaks=seq(0, max(data_topi$total_nb)+1, 1), main="Number of capture events containing 0, 1, 2, ... topi",
     xlab="Number of individuals", ylab="Number of capture events")

## Boxplots
#~# Exercise: Represent the distribution of total number of individuals across study sites according to the species using sp_per_site. Give a title
# to your graph and label axes
boxplot(data$total_nb~data$species, main="Nb of indiv according to the species", xlab="Species", ylab="Nb indiv")
boxplot(data$total_nb~data$species, main="Nb of indiv according to the species", xlab="Species", ylab="Nb indiv",
        ylim=c(0, 20)) # zoom in the range 0:20

## Scatter plot
#~# Exercise: Represent the total number of topi vs. the total number of hartebeest per site for the sites where both species have been observed.
# To do so, you need to keep only the sites where both species have been observed. You can store the new data frame in the object "sp_per_site_3".
# Do not forget to give a title to your graph and label axes
data2 <- data[is.na(data$topi)==F & is.na(data$hartebeest)==F, ]
plot(data$sup_twelve~data$adult, pch=16, main="Nb of topi vs. nb of hartebeests per site", xlab="Nb hartebeest", ylab="Nb topi")

## Stacked bar chart
#~# Exercise: Represent the total number of individuals in each age class according to the species using the data set

mosaicplot(data$total_nb~data$species, main="Nb of indiv per age class according to species", xlab="Age class", ylab="Species")
tab$species <- as.factor(tab$species)
tab$age_class <- as.factor(tab$age_class)
plot(tab$species~tab$age_class, main="Nb of indiv per age class according to species", xlab="Abundance", ylab="Species")


### 8 - Saving data #################################################################################################################################

## Save as .csv file: Easy to read outside R BUT just for data frames
write.csv2(data, file="exercise_data.csv")

## Save as .RData file: Easy to share for other R users + can save any R structures BUT can only be opened in R

